### ISSUE TITLE
ActiveSupport 2.3.15 undefined method 'mattr_accessor'

### ISSUE THREAD

**Issue by XavierMeunier** [xinminlabs/synvert#38]
I just install synvert gem but it seems it's not working with rails 2.3.15
I would like to use the gem to upgrade to rails 3 then rails 4.

I get these errors :

When I use synvert -l

    /Users/men/.rvm/gems/ruby-1.8.7-p358@rails2315b/gems/activesupport-2.3.18/lib/active_support/deprecation.rb:5: undefined method `mattr_accessor' for ActiveSupport::Deprecation:Module (NoMethodError)

When I launch my app

    /Users/men/.rvm/gems/ruby-1.8.7-p358@rails2315b/gems/activesupport-2.3.15/lib/active_support/dependencies.rb:182:in `require': /Users/men/.rvm/gems/ruby-1.8.7-p358@rails2315b/gems/synvert-core-0.9.0/lib/synvert/core/node_ext.rb:337: invalid regular expression; there's no previous pattern, to which '{' would define cardinality at 1: /{{(.*?)}}/ (SyntaxError)

**Comment by flyerhzm** [comment]
@XavierMeunier as you are using rvm, would you mind install ruby 1.9 or newer, then install and run synvert again?

**Comment by XavierMeunier** [comment]
Sorry, I didn't see this part in the README
> Synvert is tested against MRI 1.9.3, 2.0.0 and 2.1.1.

It works on 2.0.0. Thanks
